### ISSUE TITLE
GNOME 45 support

### ISSUE THREAD

**Issue by alizehctl** [maweil/gnome-shell-extension-mumble-ping#8]
MumblePing doesn't work on the latest GNOME release, since GJS has shifted to using ES modules. Are there any plans to update the extension for the latest releases? What would that work involve?

**Comment by maweil** [comment]
I already started working on GNOME 45 support, I just need a bit more time to finish it.
I would expect this to take 1-2 weeks in total to get the new version released.

In addition to migrating to ES Modules, the `Me` import is gone now and things that were previously recommended but not required (e.g. implementing the `fillPreferencesWindow` in `prefs.js` seem to be required now.

**Comment by alizehctl** [comment]
That's great to hear! Thank you for your work
